/**
 * nix-ionic-example — main entry
 *
 * Demonstrates the recommended setup pattern for a production nix-ionic app:
 *
 *   1. Import Ionic Core CSS
 *   2. Import "virtual:nix-ionic/registration" — auto-generated by the Vite plugin
 *      (registers only the <ion-*> tags and icons detected in your html`` templates)
 *   3. createRouter() — set up the Nix.js core router with hash mode
 *   4. new NavigationManager() — central navigation authority with hooks
 *   5. new IonRouterOutlet(routes, { tabs, cachePolicy, navigation }) — the engine
 *   6. createBottomTabBar() — reactive tab bar
 *   7. mount() — render the app
 *
 * On native (Capacitor), createCapacitorApp() wires StatusBar, SplashScreen,
 * and hardware back button. On web, all Capacitor calls are no-ops.
 */

// --- Ionic Core CSS ---
import "@ionic/core/css/core.css";
import "@ionic/core/css/normalize.css";
import "@ionic/core/css/structure.css";
import "@ionic/core/css/typography.css";
import "@ionic/core/css/padding.css";
import "@ionic/core/css/float-elements.css";
import "@ionic/core/css/flex-utils.css";
import "@ionic/core/css/display.css";

// --- Nix.js core ---
import { NixComponent, html, mount, nixRouter, createRouter } from "@deijose/nix-js";

// --- Nix Ionic ---
import {
    IonRouterOutlet,
    createBottomTabBar,
    NavigationManager,
    type RouteDefinition,
} from "@deijose/nix-ionic";

// --- Auto-generated registration module (Vite plugin) ---
// This imports only the <ion-*> components and ionicons detected in your
// html`` templates and calls initializeNixIonic() + registerIonicComponents().
// Remove this line if you prefer manual registration.
import "virtual:nix-ionic/registration";

// --- Pages ---
import { HomePage } from "./pages/HomePage";
import { SearchPage } from "./pages/SearchPage";
import { ProfilePage } from "./pages/ProfilePage";
import { SettingsPage } from "./pages/SettingsPage";
import { DetailPage } from "./pages/DetailPage";

// --- Optional: Capacitor bootstrap (no-op on web) ---
import { isNative, createCapacitorApp } from "@deijose/nix-ionic/capacitor";

// =============================================================
// Router setup
// =============================================================

// Hash mode works under any base path (file://, subdirectories, Capacitor)
createRouter(
    [
        { path: "/" },
        { path: "/search" },
        { path: "/profile" },
        { path: "/profile/edit" },
        { path: "/settings" },
        { path: "/settings/about" },
        { path: "/detail/:id" },
        { path: "*" }, // fallback
    ],
    { mode: "hash" },
);

// =============================================================
// NavigationManager — central navigation authority
// =============================================================

const nav = new NavigationManager({
    tabs: ["/", "/search", "/profile", "/settings"],
});

// Hooks are registered via methods (not constructor options)
nav.beforeNav((to: string, _intent) => {
    console.log(`[nav] navigating to ${to}`);
    return true; // return false to cancel
});

nav.afterNav((to: string, _direction) => {
    // e.g. analytics, scroll restoration
    console.log(`[nav] arrived at ${to}`);
});

nav.onTabChange((tab: string, _previousTab) => {
    console.log(`[tab] switched to ${tab}`);
});

// =============================================================
// Routes
// =============================================================

const routes: RouteDefinition[] = [
    // --- Home tab ---
    {
        path: "/",
        component: (ctx) => new HomePage(ctx),
    },

    // --- Search tab ---
    {
        path: "/search",
        component: (ctx) => SearchPage(ctx),
        // Per-route cache policy: keep last 5 search results
        cache: { max: 5, strategy: "lru" },
    },

    // --- Profile tab ---
    {
        path: "/profile",
        component: (ctx) => new ProfilePage(ctx),
    },
    {
        path: "/profile/edit",
        component: (ctx) => new ProfilePage(ctx),
    },

    // --- Settings tab ---
    {
        path: "/settings",
        component: (ctx) => new SettingsPage(ctx),
        // Settings page is always fresh (no cache)
        cache: false,
    },
    {
        path: "/settings/about",
        component: (ctx) => new SettingsPage(ctx),
    },

    // --- Detail (pushed on top of any tab) ---
    {
        path: "/detail/:id",
        component: (ctx) => new DetailPage(ctx),
        // Cache detail pages for 30 seconds
        cache: { ttl: 30_000 },
    },
];

// =============================================================
// IonRouterOutlet — the navigation engine
// =============================================================

const outlet = new IonRouterOutlet(routes, {
    tabs: ["/", "/search", "/profile", "/settings"],

    // Outlet-level cache policy: LRU with max 10 entries
    cachePolicy: { max: 10, strategy: "lru" },

    // Delegate stack management and hooks to NavigationManager
    navigation: nav,
});

// =============================================================
// Tab bar — reactive, hides on certain paths
// =============================================================

const tabBar = createBottomTabBar(
    [
        {
            label: "Home",
            icon: "home",
            activeIcon: "home",
            path: "/",
        },
        {
            label: "Search",
            icon: "search",
            activeIcon: "search",
            path: "/search",
        },
        {
            label: "Profile",
            icon: "person",
            activeIcon: "person",
            path: "/profile",
        },
        {
            label: "Settings",
            icon: "settings",
            activeIcon: "settings",
            path: "/settings",
        },
    ],
    {
        // Hide tab bar on detail pages and modal-edit pages
        hiddenPaths: ["/detail/*", "/profile/edit"],
    },
);

// =============================================================
// App component
// =============================================================

class App extends NixComponent {
    override render() {
        return html`
            <ion-app>
                ${outlet}
                ${tabBar}
            </ion-app>
        `;
    }
}

// =============================================================
// Capacitor bootstrap (optional — no-op on web)
// =============================================================

if (isNative()) {
    const capApp = createCapacitorApp({
        statusBar: { backgroundColor: "#3880ff", overlaysWebView: false },
        splashScreen: { fadeOutDuration: 300 },
        backButton: { defaultHref: "/" },
    });
    capApp.ready().then(() => {
        console.log("[capacitor] app ready");
    });
}

// =============================================================
// Mount
// =============================================================

// Ensure initial hash is "#/" so back() works correctly
if (!window.location.hash) {
    window.location.hash = "#/";
}

// Expose router for debugging
(window as any).__router = nixRouter();
(window as any).__nav = nav;

mount(new App(), "#app");
